# ç«™ç‚¹è®¾ç½®
site_name: çš“æ´‹æˆé•¿å‘¨è®°
site_description: è®°å½•çš“æ´‹æˆé•¿è¿‡ç¨‹ä¸­çš„ç‚¹ç‚¹æ»´æ»´
site_url: https://www.luoclan.com/
site_author: LuoClan

# ä¸»é¢˜è®¾ç½®
theme:
  # material ä¸»é¢˜
  name: material
  # è‡ªå®šä¹‰ç´ ææ–‡ä»¶å¤¹åœ°å€
  custom_dir: docs/resources/
  # favicon è®¾ç½®
  favicon: resources/favicon.ico
  # logo è®¾ç½®
  logo: resources/logo.webp
  # å­—ä½“è®¾ç½®
  font:
    code: Roboto Mono
    text: Roboto
  # è¯­è¨€è®¾ç½®
  language: zh
  # å¯¼èˆªè®¾ç½®
  features:
  # æ·»åŠ ä»£ç æ“ä½œçš„æŒ‰é’®
  #- content.action.edit
  # ç²˜æ€§å¯¼èˆªé€‰é¡¹å¡
  - navigation.tabs
  - navigation.tabs.sticky
  # å¯¼èˆªæ‰©å±•
  - navigation.expand
  # èŠ‚ç´¢å¼•é¡µ
  - navigation.indexes
  # å¯¼èˆªéƒ¨åˆ†
  - navigation.sections
  # è¿”å›é¡¶éƒ¨æŒ‰é’®
  - navigation.top
  # é”šç‚¹è·Ÿè¸ª
  - navigation.tracking
  # æœç´¢çªå‡ºæ˜¾ç¤º
  - search.highlight
  # æœç´¢å…±äº«
  - search.share
  # æœç´¢å»ºè®®
  - search.suggest
  # åˆ‡æ¢æš—é»‘æ¨¡å¼
  palette:
  - accent: indigo
    primary: white
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - accent: black
    primary: black
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  # ä»…æœç´¢ç´¢å¼•ç¡®å®šæœç´¢æ’ä»¶åº”è¯¥åªç”Ÿæˆæœç´¢ç´¢å¼•è¿˜æ˜¯ç”Ÿæˆå®Œæ•´çš„æœç´¢è§£å†³æ–¹æ¡ˆã€‚
  search_index_only: true

# é¡µè§’è®¾ç½®
# é¡µè§’ç‰ˆæƒå£°æ˜
copyright: Copyright &copy; 2023 <a href="https://www.luoclan.com">LuoClan.com</a>
extra:
  # å…³é—­ â€œMade with Material for MkDocsâ€
  generator: false
  # ç¤¾äº¤é“¾æ¥
  social:
  - icon: fontawesome/solid/blog
    link: https://www.luoclan.com
  - icon: fontawesome/solid/envelope
    link: mailto:luoclan@gmail.com

# é¢å¤– css åŠ è½½ (åŒ…æ‹¬å­—ä½“)
extra_css:
- resources/css/ui.css
- https://gw.alipayobjects.com/os/k/font/lxgwwenkaiscreenr.css

# æ§åˆ¶ç”¨äºé“¾æ¥åˆ°æ–‡æ¡£è€Œä¸æ˜¯"/"
use_directory_urls: false

# æ’ä»¶
plugins:
# æœç´¢åŠŸèƒ½
- search:
    separator: '[\\s\\u200b\\-]'
# åœ¨æ¯ä¸ªé¡µé¢åº•éƒ¨æ·»åŠ ä¸Šæ¬¡æ›´æ–°æ—¥æœŸå’Œåˆ›å»ºæ–‡æ¡£çš„æ”¯æŒ
#- git-revision-date-localized:
#    enable_creation_date: true
# æ·»åŠ  git ä»“åº“ä¿¡æ¯
repo_name: luoclan2023/luoclan2023.github.io
repo_url: https://github.com/luoclan2023/luoclan2023.github.io

# markdown æ‰©å±•åŠŸèƒ½
markdown_extensions:
# å¯ç”¨ SmartyPants ç‰ˆå¼æ‰©å±•
- smarty
# è¦åœ¨ï¼ˆåŒ…å«çš„ï¼‰æ‰©å±•ä¸­å¯ç”¨æ°¸ä¹…é“¾æ¥
- toc:
    permalink: []
- admonition
- def_list
- codehilite

# é¡¶éƒ¨å¯¼èˆªè®¾ç½®
nav:
- ğŸŒˆ é¦–é¡µ: ./index.md
- ğŸ° 2023å¹´å‘¨è®°: # å›¾æ ‡è®¾ç½® https://emojixd.com/
  - 2023å¹´ (04-17~04-23): ./2023/çš“æ´‹æˆé•¿å‘¨è®°.2023å¹´(04-17~04-23).md
  - 2023å¹´ (04-10~04-16): ./2023/çš“æ´‹æˆé•¿å‘¨è®°.2023å¹´(04-10~04-16).md
#- ğŸ”— RSSè®¢é˜…: ./rss/rss.xml